### ISSUE TITLE
Can you share a copy of the 37 blendshapes model files ? 

### ISSUE THREAD

**Issue by lith0613** [pkhungurn/talking-head-anime-2-demo#11]
I have never thought about the reverse problem before, so I don't know.

_Originally posted by @dragonmeteor in https://github.com/pkhungurn/talking-head-anime-2-demo/issues/5#issuecomment-830534833_

Thanks for your wondful project ! But I can not find the MMD model file with 37 blendshape, can you share me a copy of your MMD model file ? or just 37 blendshape mesh file, maybe obj file ?

**Comment by dragonmeteor** [comment]
Please refer to the writeup (https://pkhungurn.github.io/talking-head-anime-2/full.html#problem-spec) to see where the 37 blendshapes come from. Here's an excerpt:

"The remaining 37 parameters come from 37 common blendshapes in the MMD models I used to create the training data." Table 5.3 list how many blendshapes I have identified.

Unfortunately, I cannot share the blendshapes with you because of two problems:
(1) There's just too many models. My dataset contains about 8,000 MMD models, and each model's blendshapes are not compatible with most of other models.
(2) Almost all models are copyrighted to their creators, who mostly prohibiting sharing downloaded model data with others.

**Comment by dragonmeteor** [comment]
One more thing: the 37 blendshapes are "common" blendshapes found in 8,000 MMD models where "common" means "frequently occuring," not "shared." This means that, for each blendshape, there are many models that have them. It does not mean all 8,000 models have these 37 blendshapes. I'm not even sure that there's a model that has all of them.

**Comment by lith0613** [comment]
> One more thing: the 37 blendshapes are "common" blendshapes found in 8,000 MMD models where "common" means "frequently occuring," not "shared." This means that, for each blendshape, there are many models that have them. It does not mean all 8,000 models have these 37 blendshapes. I'm not even sure that there's a model that has all of them.

OK, Thansk so much for your reply !
