### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by graphemecluster** [pkhungurn/talking-head-anime-2-demo#2]
### Improvements
- Image are automatically resized to 256×256 now
- No more ugly output: r, g, b are changed to 0 if alpha is 0
- ~*(Content hide. See edit history for details)*~

[Fork](https://github.com/graphemecluster/talking-head-anime-2-demo/tree/main)

**Comment by dragonmeteor** [comment]
Thank you for your suggestions. However, to keep the functionality minimal, I will not be accepting such a big pull request. It's probably the best to direct people to your fork instead.

**Comment by graphemecluster** [comment]
That's OK. I don't think the first 3 points (at least, the first 2 points) will affect the minimality of the project, though.
For the fourth point I am actually seeking for someone's help for the algorithm. This is also one of the reason why I open this issue.

**Comment by graphemecluster** [comment]
I edited my fork to minimize the alternations to this repository and I would like to open a pull request because there are some mistakes found (I am not sure if they are intentional, though) and I think it is worthy of automatizing the process of alternating all pixels of (n, n, n, 0) to (0, 0, 0, 0).

Additionally, I have read some part of your article and you’ve mentioned about keypoint-based tracking. Although a direct mapping may not be possible, I wonder if you have studied in converting a set of facial landmarks returned by `dlib` to your poser’s parameter set. I think it is a simple task but I do not have enough ability to competent to this job.

いっそ日本語でも使っていきたいと思います。
素朴な疑問なのですが、顔のランドマークからこのポーサーのパラメーターに変換するアルゴリズムはどうやって作るんですか。
それに `mouth_aaa` `mouth_iii` `mouth_uuu` `mouth_eee` `mouth_ooo` のパラメーターの基準は何でしょうか……あなたの母国語にある เออ などの他の母音はどうやって調整すればいいのですか。ランドマークからは `MouthFunnel` `MouthPucker` などといった ARKit のデータはないので……何でもしますからよろしくお願いします。

**Comment by dragonmeteor** [comment]
First, if you submit a pull request with the first two improvements, I will work with you to incorporate them into the main repository. I think they are simple enhancements that make the software easier to use.

As you might have already observed, the dlib landmarks are quite enough to determine how open/close the eyes and the mouths are, so I used them in the much simpler Version 1 of the software.

Can we determine the rest of the parameters from them? I don't think so. The landmarks simply do not have enough information. For example, it does not tell you where the irises are, so you cannot determine the iris parameters from them. 

Even if you abandon the iris parameters, I also think determining other parameters would be hard. The iPhone needs an RGB capture and probably a depth image to infer the 52 blendshape parameters. Works that determine the [Action Units](https://en.wikipedia.org/wiki/Facial_Action_Coding_System) such as [EmotioNet](https://cbcsl.ece.ohio-state.edu/cvpr16.pdf) use both shape (landmark) and shading (image) cues. The landmarks, only the other hand, give you only the shape, but not the shading.

**Comment by dragonmeteor** [comment]
In the end, I think the problem you want to solve is how to control characters without having to have an iPhone. To do this, you need to be able to determine pose parameters from a video feed instead of dlib landmarks.

Guess what, I tried to solve this problem, but I gave up. I was thinking that I could leverage some free tools to do it. The most promising seemed to be [OpenFace 2](https://github.com/emilianavt/OpenSeeFace), which outputs a number of Action Units. Nonetheless, OpenFace 2 does not give me any information about the irises, so I decided to supplement it with outputs from the [MediaPipe Iris](https://google.github.io/mediapipe/solutions/iris) and [MediaPipe Face Mesh](https://google.github.io/mediapipe/solutions/face_mesh) models.

At that point, I thought I could cook up some simple formulas to reliably determine the parameters from all the outputs. I was wrong. OpenFace 2 was not at all reliable. The face mesh deformed in weird ways when the face was not looking straight ahead. I also had a hard time determining how open/close the eyes and the mouth were from OpenFace 2's landmarks and the face mesh to the point that I had to revert back to dlib landmarks to do the jobs. Nevertheless, dlib landmarks were also unstable, and the simple algorithm I used in Version 1 broke down when the face moved away from the camera. To get even passable results, I had to specify extra parameters for every video I tried to process. (Here is one such passable result: https://twitter.com/dragonmeteor/status/1329157949156061186/video/1.)

At one point, I realized that trying to solve this problem was not worth my effort. The problem I really want to solve is how to generate animations, not how to determine pose parameters from a video feed. So, I bought an iPhone and [iFacialMocap](https://www.ifacialmocap.com/), and I was able to quickly cook up [simple formulas for the parameters](https://github.com/pkhungurn/talking-head-anime-2-demo/blob/main/tha2/poser/modes/mode_20_wx.py#L130) from the blendshape parameters that it outputted. I think this decision was a good one.

So, what to do with the rest of the parameters? I don't know either. If I knew, the project would have contained many more demonstration videos. You have to do your own research. Please let me know if you are successful.

**Comment by graphemecluster** [comment]
Sorry for talking such a digressive problem and asking so much of you. I should have known that you have made great effort on it. I am glad that you shared your experiences on this problem. Thank you for reading and writing such a big essay. I must apologize if I did cause any inconvenience. I am sorry to bother you and please forgive my selfishness.
I will try my best to work on it when I have enough ability to do so.
