### ISSUE TITLE
Add upscaling feature of the modified image

### ISSUE THREAD

**Issue by xiong-jie-y** [pkhungurn/talking-head-anime-2-demo#26]
Hi!

Thank you for awesome model!

To enhance the 256x256 output of this model, I trained a realtime super resolution model that can run 50Hz.
Could you try it? If it worth embedding the model to this repository, I will make a PR.

Model Demo of real time super resolution (to check the quality)
https://huggingface.co/spaces/xiongjie/realtime-SRGAN-for-anime-example

**Comment by dragonmeteor** [comment]
I tried your model, and it seems to work well on anime images.

However, the goal of this repository is to maintain only some minimalist demos, not to develop a practical, full-blown application. So, I will not add a big feature such as what you would suggest to the repo. Sorry about that. You are free, however, to modify the code and release the result on your own if you comply with the license.

One thing to think about if you want your super-resolution model to be even more useful is the image format. The models in this repo outputs RGBA images because I assume that the outputs are going to be composited with other images later. However, your model seems to output RGB images, filling the black color whenever there is supposed to be a transparent background. This makes it harder to use the output afterwards.

**Comment by xiong-jie-y** [comment]
I see. Thanks!
