### ISSUE TITLE
About low FPS

### ISSUE THREAD

**Issue by buptorange** [pkhungurn/talking-head-anime-2-demo#6]
First thank you for the amazing work!!
I'm testing the `ifacialmocap_puppeteer.py` with single RTX3080 on Windows10, but only get FPS around 4~6.
Is this a normal performance with this GPU? Could you give me a FPS baseline  using TITAN RTX?

**Comment by bycloudai** [comment]
Thank you so much for your response
I kind of understand the situation now by what you are asking
I just thought there might be configurations that might give you FPS boost that I might have missed reading through the documentation, because the difference in FPS is pretty huge tbh.

FYI I have Win10, latest driver, no other programs using CPU/GPU

**Comment by Inversil** [comment]
What are the odds of the program becoming more light weight in the future? I have no idea how this magic works, but I was wondering if you could share any insights on potential for future improvements and/or corner-cutting that could be done.

It’s highly impressive, and an AI rig like this could make vtubing a lot more accessible than it already is! I love it.
I’d imagine that to a casual viewer this would be pretty indistinguishable from a real rig.
As things stand though, it seems like a rather expensive neural net considering the output resolution is ~250px; so even if someone invested into a 3080TI, it’s not quite practical yet.

**Comment by dragonmeteor** [comment]
Well, first, it is already faster. I discovered a bug in ifacialmocap_puppeteer that lowered the frame rate to around 10 fps on my machine instead of something higher. I fixed it, and the program constantly churned out more than 15 fps. The fix has been committed to the repository just several hours before I wrote this reply.

Second, it will be faster as there are so many ways to speed things up. 

(1) One way is to train a faster, but lower capacity model on the same data. I've experimented with using [depthwise separable convolutions](https://arxiv.org/abs/1610.02357), and it resulted in a model that was about 10 times smaller and 3 times faster. resulting in about 30 fps on my machine. I ported the model to Tensorflow.js and was able to run it on a browser: https://twitter.com/dragonmeteor/status/1398715767172964354.

(2) Another way is convert the same model to use lower-precision floating point numbers; for example, [half](https://pytorch.org/docs/stable/generated/torch.Tensor.half.html). I haven't tried this yet though.

(3) If your character is fixed, you can [distill](https://arxiv.org/abs/1503.02531) the model into a very small model that works only for that character. I've tried training a [SIREN](https://www.vincentsitzmann.com/siren/) on one: https://twitter.com/dragonmeteor/status/1382747343062061058. The model was less than 2MB in size, and inference was quite fast, but I have not really measured the speed. With a SIREN, there is no restriction on the output image's resolution, so you can zoom in as much as you want. However, bigger images requires more time to produce.

(4) Ultimately, I want to ditch deep learning at rendering time and try to infer mesh-based models (aka Live2D) from the input. I honestly don't know how to do this now, but I'm thinking hard about ways to do it.

Speed has been a major problem with the system from the start. It, however, has not been a top priority for me until last year because I wanted to solve the harder problem of adding more types of movement first. I'm now quite satisfied with the model's expressivity, so I'll be working on speed and practicality in future projects.

**Comment by FrankyCao** [comment]
> Well, first, it is already faster. I discovered a bug in ifacialmocap_puppeteer that lowered the frame rate to around 10 fps on my machine instead of something higher. I fixed it, and the program constantly churned out more than 15 fps. The fix has been committed to the repository just several hours before I wrote this reply.
> 
> Second, it will be faster as there are so many ways to speed things up.
> 
> (1) One way is to train a faster, but lower capacity model on the same data. I've experimented with using [depthwise separable convolutions](https://arxiv.org/abs/1610.02357), and it resulted in a model that was about 10 times smaller and 3 times faster. resulting in about 30 fps on my machine. I ported the model to Tensorflow.js and was able to run it on a browser: https://twitter.com/dragonmeteor/status/1398715767172964354.
> 
> (2) Another way is convert the same model to use lower-precision floating point numbers; for example, [half](https://pytorch.org/docs/stable/generated/torch.Tensor.half.html). I haven't tried this yet though.
> 
> (3) If your character is fixed, you can [distill](https://arxiv.org/abs/1503.02531) the model into a very small model that works only for that character. I've tried training a [SIREN](https://www.vincentsitzmann.com/siren/) on one: https://twitter.com/dragonmeteor/status/1382747343062061058. The model was less than 2MB in size, and inference was quite fast, but I have not really measured the speed. (Btw, I've also found a simple way to fix the problem with the eyes.) With a SIREN, there is no restriction on the output image's resolution, so you can zoom in as much as you want. However, bigger images requires more time to produce.
> 
> (4) Ultimately, I want to ditch deep learning at rendering time and try to infer mesh-based models (aka Live2D) from the input. I honestly don't know how to do this now, but I'm thinking hard about ways to do it.
> 
> Speed has been a major problem with the system from the start. It, however, has not been a top priority for me until last year because I wanted to solve the harder problem of adding more types of movement first. I'm now quite satisfied with the model's expressivity, so I'll be working on speed and practicality in future projects.


Hi,Thank you for the work
About the distill, I have a few questions
1)Which part of the model use by SIREN？
2)How long is the distillation training time and how much memory do you use during training？

**Comment by dragonmeteor** [comment]
(1) Distillation is the process of training a small model to mimic the response of a larger model (with some modification). However, in my case, I didn't do any modification, I just tried to make the smaller model (SIREN) match the response of the larger model (the whole animation pipeline). Which part is use then? The answer would be "everything."

(2) I think it took about one day. I didn't record the amount of memory used.

**Comment by FrankyCao** [comment]
> (1) Distillation is the process of training a small model to mimic the response of a larger model (with some modification). However, in my case, I didn't do any modification, I just tried to make the smaller model (SIREN) match the response of the larger model (the whole animation pipeline). Which part is use then? The answer would be "everything."
> 
> (2) I think it took about one day. I didn't record the amount of memory used.

Is that so?
<img width="819" alt="image" src="https://user-images.githubusercontent.com/7733972/155957939-751a8f88-cf2f-4ed3-94c5-a30448a9a454.png">
